--Retailers who generated highest business

SELECT
    R.RETAILER_NAME, TEMP2.SALES
FROM
    (
        SELECT
            TEMP.RETAILER_ID, TEMP.SALES, MAX(TEMP.SALES) OVER () AS MAX_SALES
        FROM
        (
            SELECT
                RETAILER_ID, SUM(AMOUNT) AS SALES
            FROM
                Fall22_S001_3_ORDERS
            WHERE
                ORDER_DATE BETWEEN '01-JAN-2022' AND '31-DEC-2022'
            GROUP BY
                RETAILER_ID
        ) TEMP
    ) TEMP2, Fall22_S001_3_RETAILERS R
WHERE
    TEMP2.RETAILER_ID = R.RETAILER_ID AND
    TEMP2.SALES = TEMP2.MAX_SALES;

SELECT R.RETAILER_NAME, TEMP2.SALES FROM (SELECT TEMP.RETAILER_ID, TEMP.SALES, MAX(TEMP.SALES) OVER () AS MAX_SALES FROM (SELECT RETAILER_ID, SUM(AMOUNT) AS SALES FROM Fall22_S001_3_ORDERS WHERE ORDER_DATE BETWEEN ? AND ? GROUP BY RETAILER_ID) TEMP) TEMP2, Fall22_S001_3_RETAILERS R WHERE TEMP2.RETAILER_ID = R.RETAILER_ID AND TEMP2.SALES = TEMP2.MAX_SALES

--Most sold products within a specific time frame

SELECT
    P.PRODUCT_NAME, TEMP2.UNITS_SOLD
FROM
    (
        SELECT
            TEMP.PRODUCT_ID, TEMP.UNITS_SOLD, MAX(TEMP.UNITS_SOLD) OVER () AS MAX_NUM
        FROM
        (
            SELECT
                CO.PRODUCT_ID, SUM(CO.PRODUCT_QUANTITY) AS UNITS_SOLD
            FROM
                Fall22_S001_3_CONTAINS_ORDERS CO, Fall22_S001_3_ORDERS O
            WHERE
                CO.ORDER_ID = O.ORDER_ID AND
                O.ORDER_DATE BETWEEN '01-JAN-2022' AND '31-DEC-2022'
            GROUP BY
                CO.PRODUCT_ID
        ) TEMP
    ) TEMP2, Fall22_S001_3_PRODUCTS P
WHERE
    TEMP2.PRODUCT_ID = P.PRODUCT_ID AND
    TEMP2.UNITS_SOLD = TEMP2.MAX_NUM;

SELECT P.PRODUCT_NAME, TEMP2.UNITS_SOLD FROM (SELECT TEMP.PRODUCT_ID, TEMP.UNITS_SOLD, MAX(TEMP.UNITS_SOLD) OVER () AS MAX_NUM FROM (SELECT CO.PRODUCT_ID, SUM(CO.PRODUCT_QUANTITY) AS UNITS_SOLD FROM Fall22_S001_3_CONTAINS_ORDERS CO, Fall22_S001_3_ORDERS O WHERE CO.ORDER_ID = O.ORDER_ID AND O.ORDER_DATE BETWEEN ? AND ? GROUP BY CO.PRODUCT_ID) TEMP) TEMP2, Fall22_S001_3_PRODUCTS P WHERE TEMP2.PRODUCT_ID = P.PRODUCT_ID AND TEMP2.UNITS_SOLD = TEMP2.MAX_NUM

--Most damaged products within a specific time frame

--Retailers from whom highest business is generated per region.

SELECT
    TEMP3.*
FROM
    (
        SELECT
            R1.REGION_ID, R1.REGION_NAME, RT1.RETAILER_ID, RT1.RETAILER_NAME, SUM(O1.AMOUNT) AS BUSINESS_SALES
        FROM
            Fall22_S001_3_ORDERS O1, Fall22_S001_3_RETAILERS RT1, Fall22_S001_3_REGIONS R1
        WHERE
            RT1.RETAILER_ID = O1.RETAILER_ID AND
            RT1.REGION_ID = R1.REGION_ID
        GROUP BY
            R1.REGION_ID, R1.REGION_NAME, RT1.RETAILER_ID, RT1.RETAILER_NAME
    ) TEMP3,
    (
        SELECT
            TEMP.REGION_ID, TEMP.REGION_NAME, MAX(TEMP.SALES) AS HIGHEST_SALES_PER_REGION
        FROM (
                SELECT
                    R.REGION_ID, R.REGION_NAME, SUM(O.AMOUNT) AS SALES
                FROM
                    Fall22_S001_3_ORDERS O, Fall22_S001_3_RETAILERS RT, Fall22_S001_3_REGIONS R
                WHERE
                    RT.RETAILER_ID = O.RETAILER_ID AND
                    RT.REGION_ID = R.REGION_ID
                GROUP BY
                    R.REGION_ID, R.REGION_NAME, RT.RETAILER_ID
            ) TEMP
        GROUP BY
            TEMP.REGION_ID, TEMP.REGION_NAME
    ) TEMP2
WHERE
    TEMP3.REGION_ID = TEMP2.REGION_ID AND
    TEMP3.BUSINESS_SALES = TEMP2.HIGHEST_SALES_PER_REGION
ORDER BY
    TEMP3.REGION_ID;

--Retailers from whom highest business is generated per region using OVER clause.

SELECT
    TEMP7.REGION_ID, TEMP7.REGION_NAME, TEMP7.RETAILER_ID, TEMP7.RETAILER_NAME, TEMP7.SALES
FROM
    (
        SELECT
            TEMP6.REGION_ID, TEMP6.REGION_NAME, TEMP6.RETAILER_ID, TEMP6.RETAILER_NAME, TEMP6.SALES, MAX(TEMP6.SALES) OVER (PARTITION BY TEMP6.REGION_ID) AS HIGHEST_SALES_PER_REGION
        FROM (
                SELECT
                    R.REGION_ID, R.REGION_NAME, RT.RETAILER_ID, RT.RETAILER_NAME, SUM(O.AMOUNT) AS SALES
                FROM
                    Fall22_S001_3_ORDERS O, Fall22_S001_3_RETAILERS RT, Fall22_S001_3_REGIONS R
                WHERE
                    RT.RETAILER_ID = O.RETAILER_ID AND
                    RT.REGION_ID = R.REGION_ID
                GROUP BY
                    R.REGION_ID, R.REGION_NAME, RT.RETAILER_ID, RT.RETAILER_NAME
            ) TEMP6
    ) TEMP7
WHERE
    TEMP7.SALES = TEMP7.HIGHEST_SALES_PER_REGION;

SELECT TEMP7.REGION_ID, TEMP7.REGION_NAME, TEMP7.RETAILER_ID, TEMP7.RETAILER_NAME, TEMP7.SALES FROM (SELECT TEMP6.REGION_ID, TEMP6.REGION_NAME, TEMP6.RETAILER_ID, TEMP6.RETAILER_NAME, TEMP6.SALES, MAX(TEMP6.SALES) OVER (PARTITION BY TEMP6.REGION_ID) AS HIGHEST_SALES_PER_REGION FROM (SELECT R.REGION_ID, R.REGION_NAME, RT.RETAILER_ID, RT.RETAILER_NAME, SUM(O.AMOUNT) AS SALES FROM Fall22_S001_3_ORDERS O, Fall22_S001_3_RETAILERS RT, Fall22_S001_3_REGIONS R WHERE RT.RETAILER_ID = O.RETAILER_ID AND RT.REGION_ID = R.REGION_ID GROUP BY R.REGION_ID, R.REGION_NAME, RT.RETAILER_ID, RT.RETAILER_NAME) TEMP6) TEMP7 WHERE TEMP7.SALES = TEMP7.HIGHEST_SALES_PER_REGION

--Top 10 most sold products throughout.

SELECT
    P1.PRODUCT_ID, P1.PRODUCT_NAME, TEMP3.UNITS_SOLD
FROM
    Fall22_S001_3_PRODUCTS P1,
    (
        SELECT
            CO.PRODUCT_ID, SUM(CO.PRODUCT_QUANTITY) AS UNITS_SOLD
        FROM
            Fall22_S001_3_CONTAINS_ORDERS CO
        GROUP BY
            CO.PRODUCT_ID
    ) TEMP3
WHERE
    P1.PRODUCT_ID = TEMP3.PRODUCT_ID
ORDER BY TEMP3.UNITS_SOLD DESC
FETCH FIRST 10 ROWS ONLY;

--Assuming that all the damages happen when a sales person drives rash, find out the sales person responsible for most of the damages
--in terms of the total units damaged

SELECT
    SP2.SALES_PERSON_ID, SP2.FIRST_NAME, SP2.LAST_NAME, TEMP5.SP_DAMAGED_UNITS
FROM
    Fall22_S001_3_SALES_PERSON SP2,
    (
    SELECT
        SP.SALES_PERSON_ID, SUM(TEMP4.RETAILER_DAMAGED_UNITS) AS SP_DAMAGED_UNITS
    FROM
        Fall22_S001_3_RETAILERS R2, Fall22_S001_3_REGIONS RG, Fall22_S001_3_ROUTES RO, Fall22_S001_3_SALES_PERSON SP,
        (
            SELECT
                O.RETAILER_ID, SUM(CN.PRODUCT_QUANTITY) AS RETAILER_DAMAGED_UNITS
            FROM
                Fall22_S001_3_CONTAINS_CN CN, Fall22_S001_3_CREDIT_NOTES C, Fall22_S001_3_ORDERS O
            WHERE
                CN.CREDIT_NOTE_ID = C.CREDIT_NOTE_ID AND
                C.ORDER_ID = O.ORDER_ID
            GROUP BY
                O.RETAILER_ID
        ) TEMP4
    WHERE
        TEMP4.RETAILER_ID = R2.RETAILER_ID AND
        R2.REGION_ID = RG.REGION_ID AND
        RG.ROUTE_ID = RO.ROUTE_ID AND
        RO.SALES_PERSON_ID = SP.SALES_PERSON_ID
    GROUP BY
        SP.SALES_PERSON_ID
    ) TEMP5
WHERE
    SP2.SALES_PERSON_ID = TEMP5.SALES_PERSON_ID
ORDER BY
    TEMP5.SP_DAMAGED_UNITS DESC
FETCH FIRST 1 ROWS ONLY;

-- Give the no of units sold
--     Per product then,
--     Per product and per region then,
--     Per product, per region and per retailer then,
--     In total,

SELECT
    CO.PRODUCT_ID, RG.REGION_ID, O.RETAILER_ID, SUM(CO.PRODUCT_QUANTITY) AS UNITS_SOLD
FROM
    Fall22_S001_3_CONTAINS_ORDERS CO, Fall22_S001_3_ORDERS O, Fall22_S001_3_RETAILERS R, Fall22_S001_3_REGIONS RG
WHERE
    CO.ORDER_ID = O.ORDER_ID AND
    O.RETAILER_ID = R.RETAILER_ID AND
    R.REGION_ID = RG.REGION_ID
GROUP BY ROLLUP(CO.PRODUCT_ID, RG.REGION_ID, O.RETAILER_ID);


-- Give the no of units damaged
--     Per product then,
--     Per product and per region then,
--     Per product, per region and per retailer then,
--     In total, 

SELECT
    CO.PRODUCT_ID, RG.REGION_ID, P.RETAILER_ID, SUM(CO.PRODUCT_QUANTITY) AS UNITS_DAMAGED
FROM
    Fall22_S001_3_CONTAINS_CN CO, Fall22_S001_3_CREDIT_NOTES O, Fall22_S001_3_ORDERS P, Fall22_S001_3_RETAILERS R, Fall22_S001_3_REGIONS RG
WHERE
    CO.CREDIT_NOTE_ID = O.CREDIT_NOTE_ID AND
    O.ORDER_ID = P.ORDER_ID AND
    P.RETAILER_ID = R.RETAILER_ID AND
    R.REGION_ID = RG.REGION_ID
GROUP BY ROLLUP(CO.PRODUCT_ID, RG.REGION_ID, P.RETAILER_ID);