DECLARE CNT NUMBER;

BEGIN
    SELECT COUNT(*) INTO CNT FROM USER_TABLES WHERE TABLE_NAME LIKE '%FALL22_S001_3_CONTAINS_ORDERS%';
    IF CNT <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE FALL22_S001_3_CONTAINS_ORDERS PURGE';
    END IF;

    SELECT COUNT(*) INTO CNT FROM USER_TABLES WHERE TABLE_NAME LIKE '%FALL22_S001_3_CONTAINS_CN%';
    IF CNT <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE FALL22_S001_3_CONTAINS_CN PURGE';
    END IF;

    SELECT COUNT(*) INTO CNT FROM USER_TABLES WHERE TABLE_NAME LIKE '%FALL22_S001_3_CREDIT_NOTES%';
    IF CNT <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE FALL22_S001_3_CREDIT_NOTES PURGE';
    END IF;

    SELECT COUNT(*) INTO CNT FROM USER_TABLES WHERE TABLE_NAME LIKE '%FALL22_S001_3_ORDERS%';
    IF CNT <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE FALL22_S001_3_ORDERS PURGE';
    END IF;

    SELECT COUNT(*) INTO CNT FROM USER_TABLES WHERE TABLE_NAME LIKE '%FALL22_S001_3_RETAILERS%';
    IF CNT <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE FALL22_S001_3_RETAILERS PURGE';
    END IF;

    SELECT COUNT(*) INTO CNT FROM USER_TABLES WHERE TABLE_NAME LIKE '%FALL22_S001_3_REGIONS%';
    IF CNT <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE FALL22_S001_3_REGIONS PURGE';
    END IF;

    SELECT COUNT(*) INTO CNT FROM USER_TABLES WHERE TABLE_NAME LIKE '%FALL22_S001_3_ROUTES%';
    IF CNT <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE FALL22_S001_3_ROUTES PURGE';
    END IF;

    SELECT COUNT(*) INTO CNT FROM USER_TABLES WHERE TABLE_NAME LIKE '%FALL22_S001_3_SALES_PERSON_CONTACT%';
    IF CNT <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE FALL22_S001_3_SALES_PERSON_CONTACT PURGE';
    END IF;

    SELECT COUNT(*) INTO CNT FROM USER_TABLES WHERE TABLE_NAME LIKE '%FALL22_S001_3_SALES_PERSON%';
    IF CNT <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE FALL22_S001_3_SALES_PERSON PURGE';
    END IF;

    SELECT COUNT(*) INTO CNT FROM USER_TABLES WHERE TABLE_NAME LIKE '%FALL22_S001_3_PRODUCTS%';
    IF CNT <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE FALL22_S001_3_PRODUCTS PURGE';
    END IF;

    SELECT COUNT(*) INTO CNT FROM USER_TABLES WHERE TABLE_NAME LIKE '%FALL22_S001_3_PRODUCT_TYPES%';
    IF CNT <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE FALL22_S001_3_PRODUCT_TYPES PURGE';
    END IF;
END;
/